version: '3.9'

services:
  librarymanagementapi:
    build:
      context: .
      dockerfile: LibraryManagementApp/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=librarydb;Username=test;Password=test
      - Jwt__Key=YourSuperSecretKeyThatIsAtLeast32CharactersLong
      - Jwt__Issuer=https://localhost:5000
      - Jwt__Audience=LibraryManagementAPI
    depends_on:
      - db

  identityapi:
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: librarydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
